/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 fluxs.gltf --transform
Author: Phil_XG (https://sketchfab.com/phil_xg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fluxs-pit-stop-6bb8bd116e384d9f9e7041dbb84e5e24
Title: Flux's Pit Stop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Fluxs(props) {
  const { nodes, materials } = useGLTF('/fluxs-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.04}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Back} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Front} />
      </group>
    </group>
  )
}

useGLTF.preload('/fluxs-transformed.glb')
